# The GitHub release configuration file: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes

changelog:
  categories:
    - title: Homebridge Apt Package Manifest
      labels:
        - "*"
